swagger: "2.0"
info:
  version: "1.0"
  title: Endless Marvels
host: localhost
basePath: /marvel/api/v1.0
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /interactions:
    post:
      responses:
        201:
          description: Created
        400:
          description: Invalid interaction field
        409:
          description: Interaction already exists with the same ID
  /interactions/{id}:
    get:
      responses:
        200:
          description: OK
      parameters:
        - name: id
          in: path
          description: ID of interaction to retrieve
          required: true
          type: string
          format: int64
  /statistics:
    get:
      responses:
        200:
          description: OK
